# All SpaceVim option below [option] section
[options]
  colorscheme = "OceanicNext"
  colorscheme_bg = "dark"
  enable_guicolors = true

  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

  default_indent = 4
  expand_tab = true

  disabled_plugins = ["Shougo#deoplete"]
 
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"

#[[layers]]
#  name = 'autocomplete'
#  auto_completion_return_key_behavior = "complete"
#  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = "denite"

[[layers]]
  name = "tools"

[[layers]]
  name = "ui"
  enable_sidebar = true

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#python"

[[layers]]
  # Notes:
  #  - Make sure racer is not installed.
  name = "lang#rust"
  format-autosave = true
  recommended-style = true

[[layers]]
  name = "lang#markdown"

[[layers]]
  # Notes:
  #  - every keystroke is sent to the language server
  #  - rls and rust-analyzer eat CPU and therefore battery
  name = "lsp"
  filetypes = [
#    "rust",
    "python"
  ]
#  [layers.override_cmd]
#    rust = ["rust-analyzer"]

[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0
